// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Addon struct {
	ID              uint64
	OrgID           uint64
	Name            string
	ActivatedByID   sql.NullInt64
	ActivatedAt     sql.NullTime
	DeactivatedByID sql.NullInt64
	DeactivatedAt   sql.NullTime
}

type Assignment struct {
	ID           uint64
	OrgID        sql.NullInt64
	DepartmentID uint64
	DivisionID   uint64
	LocationID   uint64
	Assessor     string
	Reviewer     string
	Manager      string
	UnitAdmin    string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	IsActive     bool
}

type Attachment struct {
	ID             uint64
	AttachableType string
	AttachableID   uint64
	FilePath       string
	FileName       string
	FileExt        string
	FileType       sql.NullString
	Disk           string
	Client         string
	UserID         uint64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Building struct {
	ID         uint64
	OrgID      sql.NullInt64
	Name       string
	LocationID uint64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Cache struct {
	Key        string
	Value      string
	Expiration int32
}

type CacheLock struct {
	Key        string
	Owner      string
	Expiration int32
}

type CampusMapping struct {
	ID         uint64
	LocationID sql.NullInt32
	BuildingID sql.NullInt32
	FloorID    sql.NullInt32
	ZoneID     sql.NullInt32
	SpotID     sql.NullInt32
	IsActive   bool
	CreatedBy  sql.NullInt64
	UpdatedBy  sql.NullInt64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Campuse struct {
	ID                         uint64
	OrgID                      sql.NullInt64
	LocationID                 uint64
	BuildingID                 uint64
	FloorID                    uint64
	ZoneID                     uint64
	SpotID                     uint64
	IsActive                   bool
	CreatedAt                  sql.NullTime
	UpdatedAt                  sql.NullTime
	Barcode                    sql.NullString
	Source                     string
	CanDelete                  bool
	Latitude                   sql.NullString
	Longitude                  sql.NullString
	EnabledWithoutQrSubmission bool
}

type Category struct {
	ID        uint64
	OrgID     sql.NullInt64
	Name      string
	Desc      sql.NullString
	Type      string
	Meta      json.RawMessage
	IsActive  bool
	ParentID  sql.NullInt64
	CreatedBy sql.NullInt64
	UpdatedBy sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Checklist struct {
	ID             uint64
	OrgID          sql.NullInt64
	Title          string
	Icon           sql.NullString
	Json           json.RawMessage
	Slug           sql.NullString
	IsActive       sql.NullBool
	IsLocked       bool
	IsTemplate     bool
	UserID         uint64
	UpdatedBy      sql.NullInt64
	DepartmentID   string
	DivisionID     string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	DeletedBy      sql.NullInt64
	DeviationMeta  json.RawMessage
	VisibilityMeta json.RawMessage
	Meta           json.RawMessage
	FieldsMeta     json.RawMessage
	Source         string
}

type ChecklistRevision struct {
	ID          uint64
	ChecklistID uint64
	UserID      uint64
	Json        json.RawMessage
	CreatedAt   time.Time
}

type Comment struct {
	ID           uint64
	OrgID        sql.NullInt64
	EscalationID sql.NullInt64
	TaskID       sql.NullInt64
	// Source of the comment. vop, rlst
	Source      string
	Type        string
	Content     sql.NullString
	UserID      uint64
	Commentmeta json.RawMessage
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type ConsultantCustomer struct {
	ID           uint64
	ConsultantID uint64
	CustomerID   uint64
	AddedByID    sql.NullInt64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Customer struct {
	ID                  uint64
	CompanyID           uint64
	CompanyCode         sql.NullString
	CompanyName         string
	Email               string
	PhoneNo             string
	IsActive            bool
	Meta                pqtype.NullRawMessage
	PrimaryPersonUserID sql.NullInt64
	CreatedBy           uint64
	UpdatedBy           uint64
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type Department struct {
	ID         uint64
	OrgID      sql.NullInt64
	Name       string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
	LocationID sql.NullInt64
}

type Division struct {
	ID           uint64
	OrgID        sql.NullInt64
	Name         string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	DepartmentID sql.NullInt64
}

type Entry struct {
	ID               uint64
	OrgID            uint64
	FeedbackID       uint64
	ChecklistID      uint64
	LocationID       uint64
	DepartmentID     uint64
	DivisionID       uint64
	CampusID         uint64
	IsScheduledEntry bool
	UserID           uint64
	Role             sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	Source           string
	Meta             json.RawMessage
	IsOffline        bool
}

type EntryOverride struct {
	ID            uint64
	OrgID         sql.NullInt64
	FeedbackID    uint64
	FieldID       sql.NullString
	ParentID      sql.NullInt64
	OverrideEntry json.RawMessage
	EditorID      uint64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	ApprovedBy    sql.NullInt64
	ApprovedAt    sql.NullTime
}

type Escalation struct {
	ID          uint64
	OrgID       sql.NullInt64
	FeedbackID  uint64
	ChecklistID uint64
	FieldID     string
	OverrideID  sql.NullInt64
	// F: Feedbacks, O: Override
	Type string
	// l1: Assessor,l2: Reviewer,l3: Manager,l4: Unitadmin,l5: Enterprise Admin
	Level        sql.NullString
	EscalateAt   sql.NullTime
	DepartmentID sql.NullString
	DivisionID   sql.NullString
	LocationID   sql.NullInt64
	ReviewerIds  json.RawMessage
	Status       string
	// User ID who created the escalation
	CreatedBy      sql.NullInt64
	ApprovedBy     sql.NullInt64
	ApprovedAt     sql.NullTime
	ClosedBy       sql.NullInt64
	ClosedAt       sql.NullTime
	Escalationmeta json.RawMessage
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	ResolvedBy     sql.NullInt64
	ResolvedAt     sql.NullTime
	DeletedAt      sql.NullTime
	DeletedBy      sql.NullInt64
	Source         string
}

type ExportDataJob struct {
	ID           uint64
	JobUuid      string
	OrgID        uint64
	UserID       uint64
	ParentJobID  sql.NullInt64
	Status       string
	Type         string
	Payload      json.RawMessage
	StartedAt    sql.NullTime
	CompletedAt  sql.NullTime
	ErrorMessage sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type FailedJob struct {
	ID         uint64
	Uuid       string
	Connection string
	Queue      string
	Payload    string
	Exception  string
	FailedAt   time.Time
}

type Feedback struct {
	ID                  uint64
	OrgID               sql.NullInt64
	ChecklistID         uint64
	LocationID          sql.NullInt64
	DepartmentID        sql.NullInt64
	DivisionID          sql.NullInt64
	Json                json.RawMessage
	UserID              sql.NullInt64
	Role                sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	DeletedAt           sql.NullTime
	DeletedBy           sql.NullInt64
	CampusID            uint64
	IsScheduledEntry    bool
	ApprovedBy          sql.NullInt64
	ApprovedAt          sql.NullTime
	Meta                json.RawMessage
	ReviewerVerifiedAt  sql.NullTime
	ReviewerVerifiedBy  sql.NullInt64
	ManagerVerifiedAt   sql.NullTime
	ManagerVerifiedBy   sql.NullInt64
	UnitAdminVerifiedAt sql.NullTime
	UnitAdminVerifiedBy sql.NullInt64
	ApprovalRole        sql.NullString
	Source              string
	IsOffline           bool
	TransactionID       sql.NullString
}

type Floor struct {
	ID         uint64
	OrgID      sql.NullInt64
	Name       string
	BuildingID uint64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	LocationID uint64
}

type Job struct {
	ID          uint64
	Queue       string
	Payload     string
	Attempts    uint8
	ReservedAt  sql.NullInt32
	AvailableAt uint32
	CreatedAt   uint32
}

type Location struct {
	ID          uint64
	OrgID       sql.NullInt64
	Name        string
	DisplayName sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Map struct {
	ID                         uint64
	OrgID                      sql.NullInt64
	LocationID                 uint64
	BuildingID                 uint64
	FloorID                    uint64
	ZoneID                     uint64
	SpotID                     uint64
	ChecklistID                uint64
	Barcode                    sql.NullString
	CreatedAt                  sql.NullTime
	UpdatedAt                  sql.NullTime
	CampusID                   uint64
	VisibilityMeta             json.RawMessage
	DeletedAt                  sql.NullTime
	DeletedBy                  sql.NullInt64
	EnabledOfflineSubmission   bool
	CanDelete                  bool
	IsActive                   bool
	EnabledWithoutQrSubmission bool
	SubmissionLimit            int32
}

type Migration struct {
	ID        uint32
	Migration string
	Batch     int32
}

type ModelHasPermission struct {
	PermissionID uint64
	ModelType    string
	ModelID      uint64
}

type ModelHasRole struct {
	RoleID    uint64
	ModelType string
	ModelID   uint64
}

type PasswordReset struct {
	Email     string
	Token     string
	CreatedAt sql.NullTime
}

type PdfTemplate struct {
	ID          uint64
	OrgID       uint64
	ChecklistID uint64
	Key         string
	Name        string
	Content     sql.NullString
	Meta        json.RawMessage
	IsActive    bool
	CreatedBy   uint64
	UpdatedBy   uint64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Permission struct {
	ID        uint64
	Name      string
	GuardName string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PersonalAccessToken struct {
	ID            uint64
	TokenableType string
	TokenableID   uint64
	Name          string
	Token         string
	Abilities     sql.NullString
	LastUsedAt    sql.NullTime
	ExpiresAt     sql.NullTime
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Plan struct {
	ID          uint64
	UserID      sql.NullInt64
	Name        sql.NullString
	Days        int8
	Description sql.NullString
	IsActive    bool
	CreatedBy   sql.NullInt64
	UpdatedBy   sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Role struct {
	ID        uint64
	Name      string
	GuardName string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type RoleHasPermission struct {
	PermissionID uint64
	RoleID       uint64
}

type Roster struct {
	ID               uint64
	OrgID            uint64
	RosterDate       time.Time
	TeamMappingID    sql.NullInt64
	TaskSchedulerID  sql.NullInt64
	LocationID       sql.NullInt64
	DepartmentID     sql.NullInt64
	DivisionID       sql.NullInt64
	ChecklistID      uint32
	CampusID         uint64
	StartingDatetime time.Time
	TargetDatetime   time.Time
	EndingDatetime   time.Time
	// D: Daily, W: Weekly, M: Monthly
	SchedulerType        string
	SchedulerIsActive    bool
	AnyoneCanParticipate bool
	RemovedBy            sql.NullInt64
	RemovedAt            sql.NullTime
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type Setting struct {
	ID        uint64
	OrgID     sql.NullInt64
	KeyName   string
	KeyValue  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type SlaveRoster struct {
	ID               uint64
	RosterID         uint64
	OrgID            uint64
	RosterDate       time.Time
	TeamMappingID    sql.NullInt64
	TaskSchedulerID  sql.NullInt64
	LocationID       sql.NullInt64
	DepartmentID     sql.NullInt64
	DivisionID       sql.NullInt64
	ChecklistID      uint32
	CampusID         uint64
	StartingDatetime time.Time
	TargetDatetime   time.Time
	EndingDatetime   time.Time
	// D: Daily, W: Weekly, M: Monthly
	SchedulerType        string
	SchedulerIsActive    bool
	AnyoneCanParticipate bool
	RemovedBy            sql.NullInt64
	RemovedAt            sql.NullTime
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type Spot struct {
	ID         uint64
	OrgID      sql.NullInt64
	Name       string
	ZoneID     uint64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	LocationID uint64
	BuildingID uint64
	FloorID    uint64
}

type Task struct {
	ID           uint64
	OrgID        uint64
	Title        string
	Description  sql.NullString
	Status       string
	Priority     string
	DueDate      sql.NullTime
	Meta         json.RawMessage
	Source       string
	DeleteReason sql.NullString
	CreatedBy    sql.NullInt32
	UpdatedBy    sql.NullInt32
	DeletedBy    sql.NullInt32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type TaskAssignee struct {
	ID         uint64
	OrgID      uint64
	TaskID     uint64
	UserID     uint64
	AssignedBy sql.NullInt32
	AssignedAt time.Time
	RemovedBy  sql.NullInt32
	RemovedAt  sql.NullTime
}

type TaskScheduler struct {
	ID               uint64
	OrgID            sql.NullInt64
	ChecklistSpotID  uint64
	Frequency        string
	Recurrences      json.RawMessage
	Days             json.RawMessage
	Dates            json.RawMessage
	IsActive         bool
	GraceTime        sql.NullInt16
	PreScheduledTime sql.NullInt16
	CreatedBy        uint64
	UpdatedBy        uint64
	DeletedBy        sql.NullInt64
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	DeletedAt        sql.NullTime
}

type TelescopeEntriesTag struct {
	EntryUuid string
	Tag       string
}

type TelescopeEntry struct {
	Sequence             uint64
	Uuid                 string
	BatchID              string
	FamilyHash           sql.NullString
	ShouldDisplayOnIndex bool
	Type                 string
	Content              string
	CreatedAt            sql.NullTime
}

type TelescopeMonitoring struct {
	Tag string
}

type Trial struct {
	ID        uint64
	OrgID     uint64
	PlanID    uint32
	TrialID   uint64
	StartedAt sql.NullTime
	ExpiredAt sql.NullTime
	// active, inactive, expired, completed, cancelled
	Status    string
	CreatedBy sql.NullInt64
	UpdatedBy sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID              uint64
	Email           sql.NullString
	EmailVerifiedAt sql.NullTime
	Password        string
	// 1: Active, 0: Inactive
	IsActive       bool
	ReleavedBy     uint64
	ReleavedAt     sql.NullTime
	RememberToken  sql.NullString
	Name           string
	Lname          sql.NullString
	EmpID          sql.NullString
	Doj            sql.NullTime
	Phone          sql.NullString
	DepartmentID   sql.NullInt64
	DivisionID     sql.NullInt64
	LocationID     sql.NullInt64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	Usermeta       json.RawMessage
	UserType       string
	OrgID          sql.NullInt64
	CreatedBy      sql.NullInt64
	UpdatedBy      sql.NullInt64
	FcmToken       sql.NullString
	OneSignalToken sql.NullString
}

type UserLocation struct {
	ID         uint64
	OrgID      uint64
	UserID     uint64
	LocationID uint64
	AddedBy    uint64
	AddedAt    time.Time
	RemovedBy  sql.NullInt64
	RemovedAt  sql.NullTime
}

type UserParticipation struct {
	ID           uint64
	OrgID        uint64
	RosterID     uint64
	UserID       uint64
	FeedbackID   sql.NullInt64
	LocationID   sql.NullInt64
	DepartmentID sql.NullInt64
	DivisionID   sql.NullInt64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Workflow struct {
	ID        uint64
	OrgID     uint64
	Name      string
	IsActive  bool
	CreatedBy uint64
	UpdatedBy uint64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type WorkflowAction struct {
	ID         uint64
	OrgID      uint64
	TriggerID  uint64
	ActionName string
	ConfigData json.RawMessage
	IsActive   bool
	CreatedBy  uint64
	UpdatedBy  uint64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type WorkflowTrigger struct {
	ID          uint64
	OrgID       uint64
	WorkflowID  uint64
	TriggerType string
	ChecklistID sql.NullInt64
	ConfigData  json.RawMessage
	IsActive    bool
	CreatedBy   uint64
	UpdatedBy   uint64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Zone struct {
	ID         uint64
	OrgID      sql.NullInt64
	Name       string
	FloorID    uint64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	LocationID uint64
	BuildingID uint64
}
