// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT
    id, company_id, company_code, company_name, email, phone_no, is_active, _meta, primary_person_user_id, created_by, updated_by, created_at, updated_at
from
    customers
WHERE
    id = ?
`

func (q *Queries) GetCustomerByID(ctx context.Context, id uint64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyCode,
		&i.CompanyName,
		&i.Email,
		&i.PhoneNo,
		&i.IsActive,
		&i.Meta,
		&i.PrimaryPersonUserID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomers = `-- name: GetCustomers :many
SELECT
    id, company_id, company_code, company_name, email, phone_no, is_active, _meta, primary_person_user_id, created_by, updated_by, created_at, updated_at
FROM
    customers
`

func (q *Queries) GetCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CompanyCode,
			&i.CompanyName,
			&i.Email,
			&i.PhoneNo,
			&i.IsActive,
			&i.Meta,
			&i.PrimaryPersonUserID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntries = `-- name: GetEntries :many
SELECT
    id, org_id, feedback_id
FROM
    entries
`

type GetEntriesRow struct {
	ID         uint64
	OrgID      uint64
	FeedbackID uint64
}

func (q *Queries) GetEntries(ctx context.Context) ([]GetEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesRow
	for rows.Next() {
		var i GetEntriesRow
		if err := rows.Scan(&i.ID, &i.OrgID, &i.FeedbackID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesCount = `-- name: GetEntriesCount :one
SELECT
    COUNT(*) as count
FROM
    entries
`

func (q *Queries) GetEntriesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEntriesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
